on:
    push:
        tags:
            - "*"

jobs:
    make-release:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Release
          uses: softprops/action-gh-release@v1
          id: create_release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref_name }}
            name: ${{  github.ref_name }}
            draft: true
            prerelease: false
            fail_on_unmatched_files: true