on:
    push:
        tags:
            - "*"

jobs:
    prep:
      runs-on: ubuntu-latest

      steps:
        - name: Get Version
          id: get_version
          run: |
              echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
              echo "Tag name from github.ref_name: ${{  github.ref_name }}"

    build-python:
      needs: prep
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Release
          uses: softprops/action-gh-release@v1
          id: create_release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref_name }}
            name: v${{  github.ref_name }}
            draft: true
            prerelease: false
            fail_on_unmatched_files: true